services:

  devopsdb:
    image: dbimage:v1
    ports:
      - "3306:3306"
    deploy:
      replicas: 1
      resources:
        reservations:
          cpus: "0.5"
          memory: 100M
        limits:
          cpus: "1.0"
          memory: 1000M
    volumes:
      - mydata:/var/lib/mysql

  application:
    image: appimage:v1
    ports:
      - "1111:8080"
    depends_on:
      - devopsdb
    deploy:
      replicas: 1
      resources:
        reservations:
          cpus: "0.5"
          memory: 100M
        limits:
          cpus: "1.0"
          memory: 1000M

volumes:
  mydata:
